#!/bin/bash
if [[ $# == 0 ]]; then
	# -x does both an `exist` check and and `executable` check
	if [[ -x $PAGER ]]; then
		$PAGER ~/.quick.ref
	else
		/bin/cat ~/.quick.ref
	fi
elif [[ $# == 1 ]]; then
	if [[ -e ~/.${1}.quick.ref ]]; then
		ln -sfn ~/.${1}.quick.ref ~/.quick.ref
		qref
	else
		echo "error: file not found"
	fi
else
	echo "error: invalid arg num"
fi
